#!/usr/bin/python3
import sys

def factorize(number):
    for i in range(2, number + 1):
        if number % i == 0:
            print(f"{i}*{number // i}={number}")
            break
def main():
    if len(sys.argv) < 2:
        print("Usage: ./factorize <file>")
        return

    filename = sys.argv[1]

    try:
        with open(filename, "r") as file:
            for line in file:
                number = int(line.strip())
                factorize(number)
    except FileNotFoundError:
        print("Failed to open the file.")
        return

    return

if __name__ == "__main__":
    main()
