#!/bin/bash

is_prime() {
  number=$1
  if ((number < 2)); then
    return 1
  fi

  if ((number == 2 || number == 3)); then
    return 0
  fi

  if ((number % 2 == 0 || number % 3 == 0)); then
    return 1
  fi

  i=5
  w=2
  while ((i * i <= number)); do
    if ((number % i == 0)); then
      return 1
    fi
    i=$((i + w))
    w=$((6 - w))
  done

  return 0
}

factorize() {
  number=$1

  # Handle small prime factors separately
  while ((number % 2 == 0)); do
    echo "$number=2*$((number / 2))"
    number=$((number / 2))
  done

  # Check for larger prime factors
  for ((i = 3; i * i <= number; i += 2)); do
    while ((number % i == 0)); do
      echo "$number=$i*$((number / i))"
      number=$((number / i))
    done
  done

  # If the remaining number is prime
  if ((number > 2)); then
    echo "$number=1*$number"
  fi
}

main() {
  if [[ $# -lt 1 ]]; then
    echo "Usage: factors <file>"
    return
  fi

  filename=$1

  if [[ ! -f $filename ]]; then
    echo "Failed to open the file."
    return
  fi

  while IFS= read -r line; do
    number=$(echo "$line" | awk '{$1=$1};1')
    factorize "$number"
  done < "$filename"
}

main "$@"

