#!/usr/bin/python3
import sys
import math

def factorize(number):
    sqrt_number = int(math.sqrt(number)) + 1

    for i in range(2, sqrt_number):
        if number % i == 0:
            print(f"{number}={i}*{number // i}")
            return
def main():
    if len(sys.argv) < 2:
        print("Usage: ./factorize <file>")
        return

    filename = sys.argv[1]

    try:
        with open(filename, "r") as file:
            for line in file:
                number = int(line.strip())
                factorize(number)
    except FileNotFoundError:
        print("Failed to open the file.")
        return

    return

if __name__ == "__main__":
    main()
