#!/usr/bin/python3
import sys

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False
    return True

def factorize(number):
    for i in range(2, number + 1):
        if number % i == 0 and is_prime(i):
            print(f"{number}={i}*{number // i}")
            break

def main():
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        return

    filename = sys.argv[1]

    try:
        with open(filename, "r") as file:
            for line in file:
                number = int(line.strip())
                factorize(number)
    finally:
    	return
if __name__ == '__main__':
    main()
