#!/usr/bin/python3
import sys
import math

def generate_sieve(size):
    sieve = [True] * (size + 1)
    sieve[0] = sieve[1] = False

    for i in range(2, int(math.sqrt(size)) + 1):
        if sieve[i]:
            for j in range(i * i, size + 1, i):
                sieve[j] = False

    return sieve

def factorize(number):
    sqrt_number = int(math.sqrt(number)) + 1
    sieve = generate_sieve(sqrt_number)

    for i in range(2, sqrt_number):
        if number % i == 0 and sieve[i] and sieve[number // i]:
            print(f"{number}={i}*{number // i}")
            return

def main():
    if len(sys.argv) < 2:
        print("Usage: ./factorize <file>")
        return

    filename = sys.argv[1]

    try:
        with open(filename, "r") as file:
            for line in file:
                number = int(line.strip())
                factorize(number)
    except FileNotFoundError:
        print("Failed to open the file.")
        return

if __name__ == "__main__":
    main()
